In [1]:
import pandas as pd
import numpy as np

In [2]:
cap1 = "E:/LAB/Projects/Machine_learning_for_anomally_detection/IoT23_dataset/iot_23_datasets_small/opt/Malware-Project/BigDataset/IoTScenarios/CTU-Honeypot-Capture-4-1/bro/conn.log.labeled"
cap2 = "E:/LAB/Projects/Machine_learning_for_anomally_detection/IoT23_dataset/iot_23_datasets_small/opt/Malware-Project/BigDataset/IoTScenarios/CTU-Honeypot-Capture-5-1/bro/conn.log.labeled"
cap3 = "E:/LAB/Projects/Machine_learning_for_anomally_detection/IoT23_dataset/iot_23_datasets_small/opt/Malware-Project/BigDataset/IoTScenarios/CTU-Honeypot-Capture-7-1/Somfy-01/bro/conn.log.labeled"
cap4 = "E:/LAB/Projects/Machine_learning_for_anomally_detection/IoT23_dataset/iot_23_datasets_small/opt/Malware-Project/BigDataset/IoTScenarios/CTU-IoT-Malware-Capture-1-1/bro/conn.log.labeled"
cap5 = "E:/LAB/Projects/Machine_learning_for_anomally_detection/IoT23_dataset/iot_23_datasets_small/opt/Malware-Project/BigDataset/IoTScenarios/CTU-IoT-Malware-Capture-3-1/bro/conn.log.labeled"
cap6 = "E:/LAB/Projects/Machine_learning_for_anomally_detection/IoT23_dataset/iot_23_datasets_small/opt/Malware-Project/BigDataset/IoTScenarios/CTU-IoT-Malware-Capture-7-1/bro/conn.log.labeled"
cap7 = "E:/LAB/Projects/Machine_learning_for_anomally_detection/IoT23_dataset/iot_23_datasets_small/opt/Malware-Project/BigDataset/IoTScenarios/CTU-IoT-Malware-Capture-8-1/bro/conn.log.labeled"
cap8 = "E:/LAB/Projects/Machine_learning_for_anomally_detection/IoT23_dataset/iot_23_datasets_small/opt/Malware-Project/BigDataset/IoTScenarios/CTU-IoT-Malware-Capture-9-1/bro/conn.log.labeled"
cap9 = "E:/LAB/Projects/Machine_learning_for_anomally_detection/IoT23_dataset/iot_23_datasets_small/opt/Malware-Project/BigDataset/IoTScenarios/CTU-IoT-Malware-Capture-17-1/bro/conn.log.labeled"
cap10 = "E:/LAB/Projects/Machine_learning_for_anomally_detection/IoT23_dataset/iot_23_datasets_small/opt/Malware-Project/BigDataset/IoTScenarios/CTU-IoT-Malware-Capture-20-1/bro/conn.log.labeled"
cap11 = "E:/LAB/Projects/Machine_learning_for_anomally_detection/IoT23_dataset/iot_23_datasets_small/opt/Malware-Project/BigDataset/IoTScenarios/CTU-IoT-Malware-Capture-21-1/bro/conn.log.labeled"
cap12 = "E:/LAB/Projects/Machine_learning_for_anomally_detection/IoT23_dataset/iot_23_datasets_small/opt/Malware-Project/BigDataset/IoTScenarios/CTU-IoT-Malware-Capture-33-1/bro/conn.log.labeled"
cap13 = "E:/LAB/Projects/Machine_learning_for_anomally_detection/IoT23_dataset/iot_23_datasets_small/opt/Malware-Project/BigDataset/IoTScenarios/CTU-IoT-Malware-Capture-34-1/bro/conn.log.labeled"
cap14 = "E:/LAB/Projects/Machine_learning_for_anomally_detection/IoT23_dataset/iot_23_datasets_small/opt/Malware-Project/BigDataset/IoTScenarios/CTU-IoT-Malware-Capture-35-1/bro/conn.log.labeled"
cap15 = "E:/LAB/Projects/Machine_learning_for_anomally_detection/IoT23_dataset/iot_23_datasets_small/opt/Malware-Project/BigDataset/IoTScenarios/CTU-IoT-Malware-Capture-36-1/bro/conn.log.labeled"
cap16 = "E:/LAB/Projects/Machine_learning_for_anomally_detection/IoT23_dataset/iot_23_datasets_small/opt/Malware-Project/BigDataset/IoTScenarios/CTU-IoT-Malware-Capture-39-1/bro/conn.log.labeled"
cap17 = "E:/LAB/Projects/Machine_learning_for_anomally_detection/IoT23_dataset/iot_23_datasets_small/opt/Malware-Project/BigDataset/IoTScenarios/CTU-IoT-Malware-Capture-42-1/bro/conn.log.labeled"
cap18 = "E:/LAB/Projects/Machine_learning_for_anomally_detection/IoT23_dataset/iot_23_datasets_small/opt/Malware-Project/BigDataset/IoTScenarios/CTU-IoT-Malware-Capture-43-1/bro/conn.log.labeled"
cap19 = "E:/LAB/Projects/Machine_learning_for_anomally_detection/IoT23_dataset/iot_23_datasets_small/opt/Malware-Project/BigDataset/IoTScenarios/CTU-IoT-Malware-Capture-44-1/bro/conn.log.labeled"
cap20 = "E:/LAB/Projects/Machine_learning_for_anomally_detection/IoT23_dataset/iot_23_datasets_small/opt/Malware-Project/BigDataset/IoTScenarios/CTU-IoT-Malware-Capture-48-1/bro/conn.log.labeled"
cap21 = "E:/LAB/Projects/Machine_learning_for_anomally_detection/IoT23_dataset/iot_23_datasets_small/opt/Malware-Project/BigDataset/IoTScenarios/CTU-IoT-Malware-Capture-49-1/bro/conn.log.labeled"
cap22 = "E:/LAB/Projects/Machine_learning_for_anomally_detection/IoT23_dataset/iot_23_datasets_small/opt/Malware-Project/BigDataset/IoTScenarios/CTU-IoT-Malware-Capture-52-1/bro/conn.log.labeled"
cap23 = "E:/LAB/Projects/Machine_learning_for_anomally_detection/IoT23_dataset/iot_23_datasets_small/opt/Malware-Project/BigDataset/IoTScenarios/CTU-IoT-Malware-Capture-60-1/bro/conn.log.labeled"

# 20 Malware capture Preprocessing (cap4-cap23)

### Read 20 Malware capture

In [3]:
df4 = pd.read_table(filepath_or_buffer=cap4, skiprows=10, nrows=100000)
df4.columns=['ts',
              'uid',
              'id.orig_h',
              'id.orig_p',
              'id.resp_h',
              'id.resp_p',
              'proto',
              'service',
              'duration',
              'orig_bytes',
              'resp_bytes',
              'conn_state',
              'local_orig',
              'local_resp',
              'missed_bytes',
              'history',
              'orig_pkts',
              'orig_ip_bytes',
              'resp_pkts',
              'resp_ip_bytes',
              'label']
df4.drop(df4.tail(1).index,inplace=True)

In [4]:
df5 = pd.read_table(filepath_or_buffer=cap5, skiprows=10, nrows=100000)
df5.columns=['ts',
              'uid',
              'id.orig_h',
              'id.orig_p',
              'id.resp_h',
              'id.resp_p',
              'proto',
              'service',
              'duration',
              'orig_bytes',
              'resp_bytes',
              'conn_state',
              'local_orig',
              'local_resp',
              'missed_bytes',
              'history',
              'orig_pkts',
              'orig_ip_bytes',
              'resp_pkts',
              'resp_ip_bytes',
              'label']
df5.drop(df5.tail(1).index,inplace=True)

In [5]:
df6 = pd.read_table(filepath_or_buffer=cap6, skiprows=10, nrows=100000)
df6.columns=['ts',
              'uid',
              'id.orig_h',
              'id.orig_p',
              'id.resp_h',
              'id.resp_p',
              'proto',
              'service',
              'duration',
              'orig_bytes',
              'resp_bytes',
              'conn_state',
              'local_orig',
              'local_resp',
              'missed_bytes',
              'history',
              'orig_pkts',
              'orig_ip_bytes',
              'resp_pkts',
              'resp_ip_bytes',
              'label']
df6.drop(df6.tail(1).index,inplace=True)

In [6]:
df7 = pd.read_table(filepath_or_buffer=cap7, skiprows=10, nrows=100000)
df7.columns=['ts',
              'uid',
              'id.orig_h',
              'id.orig_p',
              'id.resp_h',
              'id.resp_p',
              'proto',
              'service',
              'duration',
              'orig_bytes',
              'resp_bytes',
              'conn_state',
              'local_orig',
              'local_resp',
              'missed_bytes',
              'history',
              'orig_pkts',
              'orig_ip_bytes',
              'resp_pkts',
              'resp_ip_bytes',
              'label']
df7.drop(df7.tail(1).index,inplace=True)

In [7]:
df8 = pd.read_table(filepath_or_buffer=cap8, skiprows=10, nrows=100000)
df8.columns=['ts',
              'uid',
              'id.orig_h',
              'id.orig_p',
              'id.resp_h',
              'id.resp_p',
              'proto',
              'service',
              'duration',
              'orig_bytes',
              'resp_bytes',
              'conn_state',
              'local_orig',
              'local_resp',
              'missed_bytes',
              'history',
              'orig_pkts',
              'orig_ip_bytes',
              'resp_pkts',
              'resp_ip_bytes',
              'label']
df8.drop(df8.tail(1).index,inplace=True)

In [8]:
df9 = pd.read_table(filepath_or_buffer=cap9, skiprows=10, nrows=100000)
df9.columns=['ts',
              'uid',
              'id.orig_h',
              'id.orig_p',
              'id.resp_h',
              'id.resp_p',
              'proto',
              'service',
              'duration',
              'orig_bytes',
              'resp_bytes',
              'conn_state',
              'local_orig',
              'local_resp',
              'missed_bytes',
              'history',
              'orig_pkts',
              'orig_ip_bytes',
              'resp_pkts',
              'resp_ip_bytes',
              'label']
df9.drop(df9.tail(1).index,inplace=True)

In [9]:
df10 = pd.read_table(filepath_or_buffer=cap10, skiprows=10, nrows=100000)
df10.columns=['ts',
              'uid',
              'id.orig_h',
              'id.orig_p',
              'id.resp_h',
              'id.resp_p',
              'proto',
              'service',
              'duration',
              'orig_bytes',
              'resp_bytes',
              'conn_state',
              'local_orig',
              'local_resp',
              'missed_bytes',
              'history',
              'orig_pkts',
              'orig_ip_bytes',
              'resp_pkts',
              'resp_ip_bytes',
              'label']
df10.drop(df10.tail(1).index,inplace=True)

In [10]:
df11 = pd.read_table(filepath_or_buffer=cap11, skiprows=10, nrows=100000)
df11.columns=['ts',
              'uid',
              'id.orig_h',
              'id.orig_p',
              'id.resp_h',
              'id.resp_p',
              'proto',
              'service',
              'duration',
              'orig_bytes',
              'resp_bytes',
              'conn_state',
              'local_orig',
              'local_resp',
              'missed_bytes',
              'history',
              'orig_pkts',
              'orig_ip_bytes',
              'resp_pkts',
              'resp_ip_bytes',
              'label']
df11.drop(df11.tail(1).index,inplace=True)

In [11]:
df12 = pd.read_table(filepath_or_buffer=cap12, skiprows=10, nrows=100000)
df12.columns=['ts',
              'uid',
              'id.orig_h',
              'id.orig_p',
              'id.resp_h',
              'id.resp_p',
              'proto',
              'service',
              'duration',
              'orig_bytes',
              'resp_bytes',
              'conn_state',
              'local_orig',
              'local_resp',
              'missed_bytes',
              'history',
              'orig_pkts',
              'orig_ip_bytes',
              'resp_pkts',
              'resp_ip_bytes',
              'label']
df12.drop(df12.tail(1).index,inplace=True)

In [12]:
df13 = pd.read_table(filepath_or_buffer=cap13, skiprows=10, nrows=100000)
df13.columns=['ts',
              'uid',
              'id.orig_h',
              'id.orig_p',
              'id.resp_h',
              'id.resp_p',
              'proto',
              'service',
              'duration',
              'orig_bytes',
              'resp_bytes',
              'conn_state',
              'local_orig',
              'local_resp',
              'missed_bytes',
              'history',
              'orig_pkts',
              'orig_ip_bytes',
              'resp_pkts',
              'resp_ip_bytes',
              'label']
df13.drop(df13.tail(1).index,inplace=True)

In [13]:
df14 = pd.read_table(filepath_or_buffer=cap14, skiprows=10, nrows=100000)
df14.columns=['ts',
              'uid',
              'id.orig_h',
              'id.orig_p',
              'id.resp_h',
              'id.resp_p',
              'proto',
              'service',
              'duration',
              'orig_bytes',
              'resp_bytes',
              'conn_state',
              'local_orig',
              'local_resp',
              'missed_bytes',
              'history',
              'orig_pkts',
              'orig_ip_bytes',
              'resp_pkts',
              'resp_ip_bytes',
              'label']
df14.drop(df14.tail(1).index,inplace=True)

In [14]:
df15 = pd.read_table(filepath_or_buffer=cap15, skiprows=10, nrows=100000)
df15.columns=['ts',
              'uid',
              'id.orig_h',
              'id.orig_p',
              'id.resp_h',
              'id.resp_p',
              'proto',
              'service',
              'duration',
              'orig_bytes',
              'resp_bytes',
              'conn_state',
              'local_orig',
              'local_resp',
              'missed_bytes',
              'history',
              'orig_pkts',
              'orig_ip_bytes',
              'resp_pkts',
              'resp_ip_bytes',
              'label']
df15.drop(df15.tail(1).index,inplace=True)

In [15]:
df16 = pd.read_table(filepath_or_buffer=cap16, skiprows=10, nrows=100000)
df16.columns=['ts',
              'uid',
              'id.orig_h',
              'id.orig_p',
              'id.resp_h',
              'id.resp_p',
              'proto',
              'service',
              'duration',
              'orig_bytes',
              'resp_bytes',
              'conn_state',
              'local_orig',
              'local_resp',
              'missed_bytes',
              'history',
              'orig_pkts',
              'orig_ip_bytes',
              'resp_pkts',
              'resp_ip_bytes',
              'label']
df16.drop(df16.tail(1).index,inplace=True)

In [16]:
df17 = pd.read_table(filepath_or_buffer=cap17, skiprows=10, nrows=100000)
df17.columns=['ts',
              'uid',
              'id.orig_h',
              'id.orig_p',
              'id.resp_h',
              'id.resp_p',
              'proto',
              'service',
              'duration',
              'orig_bytes',
              'resp_bytes',
              'conn_state',
              'local_orig',
              'local_resp',
              'missed_bytes',
              'history',
              'orig_pkts',
              'orig_ip_bytes',
              'resp_pkts',
              'resp_ip_bytes',
              'label']
df17.drop(df17.tail(1).index,inplace=True)

In [17]:
df18 = pd.read_table(filepath_or_buffer=cap18, skiprows=10, nrows=100000)
df18.columns=['ts',
              'uid',
              'id.orig_h',
              'id.orig_p',
              'id.resp_h',
              'id.resp_p',
              'proto',
              'service',
              'duration',
              'orig_bytes',
              'resp_bytes',
              'conn_state',
              'local_orig',
              'local_resp',
              'missed_bytes',
              'history',
              'orig_pkts',
              'orig_ip_bytes',
              'resp_pkts',
              'resp_ip_bytes',
              'label']
df18.drop(df18.tail(1).index,inplace=True)

In [18]:
df19 = pd.read_table(filepath_or_buffer=cap19, skiprows=10, nrows=100000)
df19.columns=['ts',
              'uid',
              'id.orig_h',
              'id.orig_p',
              'id.resp_h',
              'id.resp_p',
              'proto',
              'service',
              'duration',
              'orig_bytes',
              'resp_bytes',
              'conn_state',
              'local_orig',
              'local_resp',
              'missed_bytes',
              'history',
              'orig_pkts',
              'orig_ip_bytes',
              'resp_pkts',
              'resp_ip_bytes',
              'label']
df19.drop(df19.tail(1).index,inplace=True)

In [19]:
df20 = pd.read_table(filepath_or_buffer=cap20, skiprows=10, nrows=100000)
df20.columns=['ts',
              'uid',
              'id.orig_h',
              'id.orig_p',
              'id.resp_h',
              'id.resp_p',
              'proto',
              'service',
              'duration',
              'orig_bytes',
              'resp_bytes',
              'conn_state',
              'local_orig',
              'local_resp',
              'missed_bytes',
              'history',
              'orig_pkts',
              'orig_ip_bytes',
              'resp_pkts',
              'resp_ip_bytes',
              'label']
df20.drop(df20.tail(1).index,inplace=True)

In [20]:
df21 = pd.read_table(filepath_or_buffer=cap21, skiprows=10, nrows=100000)
df21.columns=['ts',
              'uid',
              'id.orig_h',
              'id.orig_p',
              'id.resp_h',
              'id.resp_p',
              'proto',
              'service',
              'duration',
              'orig_bytes',
              'resp_bytes',
              'conn_state',
              'local_orig',
              'local_resp',
              'missed_bytes',
              'history',
              'orig_pkts',
              'orig_ip_bytes',
              'resp_pkts',
              'resp_ip_bytes',
              'label']
df21.drop(df21.tail(1).index,inplace=True)

In [21]:
df22 = pd.read_table(filepath_or_buffer=cap22, skiprows=10, nrows=100000)
df22.columns=['ts',
              'uid',
              'id.orig_h',
              'id.orig_p',
              'id.resp_h',
              'id.resp_p',
              'proto',
              'service',
              'duration',
              'orig_bytes',
              'resp_bytes',
              'conn_state',
              'local_orig',
              'local_resp',
              'missed_bytes',
              'history',
              'orig_pkts',
              'orig_ip_bytes',
              'resp_pkts',
              'resp_ip_bytes',
              'label']
df22.drop(df22.tail(1).index,inplace=True)

In [22]:
df23 = pd.read_table(filepath_or_buffer=cap23, skiprows=10, nrows=100000)
df23.columns=['ts',
              'uid',
              'id.orig_h',
              'id.orig_p',
              'id.resp_h',
              'id.resp_p',
              'proto',
              'service',
              'duration',
              'orig_bytes',
              'resp_bytes',
              'conn_state',
              'local_orig',
              'local_resp',
              'missed_bytes',
              'history',
              'orig_pkts',
              'orig_ip_bytes',
              'resp_pkts',
              'resp_ip_bytes',
              'label']
df23.drop(df23.tail(1).index,inplace=True)

### Concatenate 20 Malware capture

In [58]:
frames = [df4, df5, df6, df7, df8, df9, df10, df11, df12, df13, df14, df15, df16, df17, df18, df19, df20, df21, df22, df23]

In [59]:
df = pd.concat(frames)

In [60]:
df.head(5)

,ts,uid,id.orig_h,id.orig_p,id.resp_h,id.resp_p,proto,service,duration,orig_bytes,...,conn_state,local_orig,local_resp,missed_bytes,history,orig_pkts,orig_ip_bytes,resp_pkts,resp_ip_bytes,label
0,1525879832.01624,CDe43c1PtgynajGI6,192.168.100.103,60905.0,131.174.215.147,23.0,tcp,-,2.998796,0,...,S0,-,-,0.0,S,3.0,180.0,0.0,0.0,(empty) Malicious PartOfAHorizontalPortScan
1,1525879832.024985,CJaDcG3MZzvf1YVYI4,192.168.100.103,44301.0,91.42.47.63,23.0,tcp,-,-,-,...,S0,-,-,0.0,S,1.0,60.0,0.0,0.0,(empty) Malicious PartOfAHorizontalPortScan
2,1525879832.044975,CMBrup3BLXivSp4Avc,192.168.100.103,50244.0,120.210.108.200,23.0,tcp,-,-,-,...,S0,-,-,0.0,S,1.0,60.0,0.0,0.0,(empty) Malicious PartOfAHorizontalPortScan
3,1525879833.016171,CfHl9r3XMYtDQRrHnh,192.168.100.103,34243.0,147.7.65.203,49560.0,tcp,-,2.998804,0,...,S0,-,-,0.0,S,3.0,180.0,0.0,0.0,(empty) Benign -
4,1525879833.044906,C7USrA15nFVkniMqC5,192.168.100.103,34840.0,145.164.35.6,21288.0,tcp,-,-,-,...,S0,-,-,0.0,S,1.0,60.0,0.0,0.0,(empty) Benign -

In [26]:
df.shape

(1444674, 21)

### Label Processing

In [27]:
df["label"].value_counts()

-   Malicious   PartOfAHorizontalPortScan          578916
(empty)   Malicious   PartOfAHorizontalPortScan    247023
-   Malicious   Okiru                              163016
-   Benign   -                                     146275
-   Malicious   DDoS                               138777
(empty)   Malicious   Okiru                         99674
(empty)   Benign   -                                51534
(empty)   Malicious   C&C                            8229
-   Malicious   C&C                                  6871
(empty)   Malicious   Attack                         3814
-   Malicious   C&C-HeartBeat                         227
(empty)   Malicious   C&C-HeartBeat                   122
-   Malicious   Attack                                101
-   Malicious   C&C-FileDownload                       43
-   Malicious   C&C-Torii                              30
-   Malicious   FileDownload                           13
-   Malicious   C&C-HeartBeat-FileDownload              8
-   Malicious   C&C-Mirai                               1
Name: label, dtype: int64

In [28]:
df.loc[(df.label == '-   Malicious   PartOfAHorizontalPortScan'), 'label'] = 'PartOfAHorizontalPortScan'
df.loc[(df.label == '(empty)   Malicious   PartOfAHorizontalPortScan'), 'label'] = 'PartOfAHorizontalPortScan'
df.loc[(df.label == '-   Malicious   Okiru'), 'label'] = 'Okiru'
df.loc[(df.label == '(empty)   Malicious   Okiru'), 'label'] = 'Okiru'
df.loc[(df.label == '-   Benign   -'), 'label'] = 'Benign'
df.loc[(df.label == '(empty)   Benign   -'), 'label'] = 'Benign'
df.loc[(df.label == '-   Malicious   DDoS'), 'label'] = 'DDoS'
df.loc[(df.label == '-   Malicious   C&C'), 'label'] = 'C&C'
df.loc[(df.label == '(empty)   Malicious   C&C'), 'label'] = 'C&C'
df.loc[(df.label == '-   Malicious   Attack'), 'label'] = 'Attack'
df.loc[(df.label == '(empty)   Malicious   Attack'), 'label'] = 'Attack'
df.loc[(df.label == '-   Malicious   C&C-HeartBeat'), 'label'] = 'C&C-HeartBeat'
df.loc[(df.label == '(empty)   Malicious   C&C-HeartBeat'), 'label'] = 'C&C-HeartBeat'
df.loc[(df.label == '-   Malicious   C&C-FileDownload'), 'label'] = 'C&C-FileDownload'
df.loc[(df.label == '-   Malicious   C&C-Torii'), 'label'] = 'C&C-Torii'
df.loc[(df.label == '-   Malicious   C&C-HeartBeat-FileDownload'), 'label'] = 'C&C-HeartBeat-FileDownload'
df.loc[(df.label == '-   Malicious   FileDownload'), 'label'] = 'FileDownload'
df.loc[(df.label == '-   Malicious   C&C-Mirai'), 'label'] = 'C&C-Mirai'
df.loc[(df.label == '-   Malicious   Okiru-Attack'), 'label'] = 'Okiru-Attack'

In [29]:
df['label'].value_counts()

PartOfAHorizontalPortScan     825939
Okiru                         262690
Benign                        197809
DDoS                          138777
C&C                            15100
Attack                          3915
C&C-HeartBeat                    349
C&C-FileDownload                  43
C&C-Torii                         30
FileDownload                      13
C&C-HeartBeat-FileDownload         8
C&C-Mirai                          1
Name: label, dtype: int64

In [30]:
df['label'].value_counts().count()

12

### Drop Unnecessary Features

In [31]:
list(df.columns)

['ts',
 'uid',
 'id.orig_h',
 'id.orig_p',
 'id.resp_h',
 'id.resp_p',
 'proto',
 'service',
 'duration',
 'orig_bytes',
 'resp_bytes',
 'conn_state',
 'local_orig',
 'local_resp',
 'missed_bytes',
 'history',
 'orig_pkts',
 'orig_ip_bytes',
 'resp_pkts',
 'resp_ip_bytes',
 'label']

In [32]:
df.head(5)

,ts,uid,id.orig_h,id.orig_p,id.resp_h,id.resp_p,proto,service,duration,orig_bytes,...,conn_state,local_orig,local_resp,missed_bytes,history,orig_pkts,orig_ip_bytes,resp_pkts,resp_ip_bytes,label
0,1525879832.01624,CDe43c1PtgynajGI6,192.168.100.103,60905.0,131.174.215.147,23.0,tcp,-,2.998796,0,...,S0,-,-,0.0,S,3.0,180.0,0.0,0.0,PartOfAHorizontalPortScan
1,1525879832.024985,CJaDcG3MZzvf1YVYI4,192.168.100.103,44301.0,91.42.47.63,23.0,tcp,-,-,-,...,S0,-,-,0.0,S,1.0,60.0,0.0,0.0,PartOfAHorizontalPortScan
2,1525879832.044975,CMBrup3BLXivSp4Avc,192.168.100.103,50244.0,120.210.108.200,23.0,tcp,-,-,-,...,S0,-,-,0.0,S,1.0,60.0,0.0,0.0,PartOfAHorizontalPortScan
3,1525879833.016171,CfHl9r3XMYtDQRrHnh,192.168.100.103,34243.0,147.7.65.203,49560.0,tcp,-,2.998804,0,...,S0,-,-,0.0,S,3.0,180.0,0.0,0.0,Benign
4,1525879833.044906,C7USrA15nFVkniMqC5,192.168.100.103,34840.0,145.164.35.6,21288.0,tcp,-,-,-,...,S0,-,-,0.0,S,1.0,60.0,0.0,0.0,Benign

In [33]:
df = df.drop(columns=['ts', 'uid', 'missed_bytes', 'local_orig', 'local_resp'])

In [34]:
df.head(5)

,id.orig_h,id.orig_p,id.resp_h,id.resp_p,proto,service,duration,orig_bytes,resp_bytes,conn_state,history,orig_pkts,orig_ip_bytes,resp_pkts,resp_ip_bytes,label
0,192.168.100.103,60905.0,131.174.215.147,23.0,tcp,-,2.998796,0,0,S0,S,3.0,180.0,0.0,0.0,PartOfAHorizontalPortScan
1,192.168.100.103,44301.0,91.42.47.63,23.0,tcp,-,-,-,-,S0,S,1.0,60.0,0.0,0.0,PartOfAHorizontalPortScan
2,192.168.100.103,50244.0,120.210.108.200,23.0,tcp,-,-,-,-,S0,S,1.0,60.0,0.0,0.0,PartOfAHorizontalPortScan
3,192.168.100.103,34243.0,147.7.65.203,49560.0,tcp,-,2.998804,0,0,S0,S,3.0,180.0,0.0,0.0,Benign
4,192.168.100.103,34840.0,145.164.35.6,21288.0,tcp,-,-,-,-,S0,S,1.0,60.0,0.0,0.0,Benign

### Data Preprocessing

In [35]:
df['service'] = df['service'].str.replace('-','0')

In [36]:
df['service'].value_counts()

0       1434039
dns        4667
ssh        3794
irc        1652
http        506
dhcp          8
ssl           8
Name: service, dtype: int64

In [37]:
df['duration'] = df['duration'].str.replace('-','0')

In [38]:
df['duration'].value_counts()

0            900114
2.998791        479
2.998790        479
2.998792        453
2.998793        379
              ...
48.830661         1
49.999743         1
49.004306         1
4.841590          1
0.004484          1
Name: duration, Length: 41872, dtype: int64

In [39]:
df['orig_bytes'] = df['orig_bytes'].str.replace('-','0')

In [40]:
df['resp_bytes'] = df['resp_bytes'].str.replace('-','0')

In [41]:
df

,id.orig_h,id.orig_p,id.resp_h,id.resp_p,proto,service,duration,orig_bytes,resp_bytes,conn_state,history,orig_pkts,orig_ip_bytes,resp_pkts,resp_ip_bytes,label
0,192.168.100.103,60905.0,131.174.215.147,23.0,tcp,0,2.998796,0,0,S0,S,3.0,180.0,0.0,0.0,PartOfAHorizontalPortScan
1,192.168.100.103,44301.0,91.42.47.63,23.0,tcp,0,0,0,0,S0,S,1.0,60.0,0.0,0.0,PartOfAHorizontalPortScan
2,192.168.100.103,50244.0,120.210.108.200,23.0,tcp,0,0,0,0,S0,S,1.0,60.0,0.0,0.0,PartOfAHorizontalPortScan
3,192.168.100.103,34243.0,147.7.65.203,49560.0,tcp,0,2.998804,0,0,S0,S,3.0,180.0,0.0,0.0,Benign
4,192.168.100.103,34840.0,145.164.35.6,21288.0,tcp,0,0,0,0,S0,S,1.0,60.0,0.0,0.0,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99994,192.168.1.195,3318.0,162.248.88.215,62336.0,tcp,0,0,0,0,OTH,C,0.0,0.0,0.0,0.0,DDoS
99995,192.168.1.195,42884.0,162.248.88.215,62336.0,tcp,0,0,0,0,OTH,C,0.0,0.0,0.0,0.0,DDoS
99996,192.168.1.195,61773.0,162.248.88.215,62336.0,tcp,0,0,0,0,OTH,C,0.0,0.0,0.0,0.0,DDoS
99997,192.168.1.195,37271.0,162.248.88.215,62336.0,tcp,0,0,0,0,OTH,C,0.0,0.0,0.0,0.0,DDoS
99998,192.168.1.195,5055.0,162.248.88.215,62336.0,tcp,0,0,0,0,OTH,C,0.0,0.0,0.0,0.0,DDoS

In [42]:
df.duration = df.duration.apply(lambda x: float(x))

In [43]:
df['orig_bytes'] = df['orig_bytes'].apply(lambda x: float(x))

In [44]:
df['resp_bytes'] = df['resp_bytes'].apply(lambda x: float(x))

In [45]:
df['id.orig_p'] = df['id.orig_p'].apply(lambda x: float(x))

In [46]:
df['id.resp_p'] = df['id.resp_p'].apply(lambda x: float(x))

In [47]:
df['resp_pkts'] = df['resp_pkts'].apply(lambda x: float(x))

In [48]:
df['orig_pkts'] = df['orig_pkts'].apply(lambda x: float(x))

In [49]:
df['orig_ip_bytes'] = df['orig_ip_bytes'].apply(lambda x: float(x))

In [50]:
df['resp_ip_bytes'] = df['resp_ip_bytes'].apply(lambda x: float(x))

In [51]:
df

,id.orig_h,id.orig_p,id.resp_h,id.resp_p,proto,service,duration,orig_bytes,resp_bytes,conn_state,history,orig_pkts,orig_ip_bytes,resp_pkts,resp_ip_bytes,label
0,192.168.100.103,60905.0,131.174.215.147,23.0,tcp,0,2.998796,0.0,0.0,S0,S,3.0,180.0,0.0,0.0,PartOfAHorizontalPortScan
1,192.168.100.103,44301.0,91.42.47.63,23.0,tcp,0,0.000000,0.0,0.0,S0,S,1.0,60.0,0.0,0.0,PartOfAHorizontalPortScan
2,192.168.100.103,50244.0,120.210.108.200,23.0,tcp,0,0.000000,0.0,0.0,S0,S,1.0,60.0,0.0,0.0,PartOfAHorizontalPortScan
3,192.168.100.103,34243.0,147.7.65.203,49560.0,tcp,0,2.998804,0.0,0.0,S0,S,3.0,180.0,0.0,0.0,Benign
4,192.168.100.103,34840.0,145.164.35.6,21288.0,tcp,0,0.000000,0.0,0.0,S0,S,1.0,60.0,0.0,0.0,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99994,192.168.1.195,3318.0,162.248.88.215,62336.0,tcp,0,0.000000,0.0,0.0,OTH,C,0.0,0.0,0.0,0.0,DDoS
99995,192.168.1.195,42884.0,162.248.88.215,62336.0,tcp,0,0.000000,0.0,0.0,OTH,C,0.0,0.0,0.0,0.0,DDoS
99996,192.168.1.195,61773.0,162.248.88.215,62336.0,tcp,0,0.000000,0.0,0.0,OTH,C,0.0,0.0,0.0,0.0,DDoS
99997,192.168.1.195,37271.0,162.248.88.215,62336.0,tcp,0,0.000000,0.0,0.0,OTH,C,0.0,0.0,0.0,0.0,DDoS
99998,192.168.1.195,5055.0,162.248.88.215,62336.0,tcp,0,0.000000,0.0,0.0,OTH,C,0.0,0.0,0.0,0.0,DDoS

In [53]:
df.fillna(0, inplace=True)

In [54]:
from sklearn.preprocessing import LabelEncoder

In [55]:
le = LabelEncoder()
df.proto = le.fit_transform(df.proto)
df.history = le.fit_transform(df.history)
df.conn_state = le.fit_transform(df.conn_state)
df.service = le.fit_transform(df.service)
df["id.orig_h"] = le.fit_transform(df["id.orig_h"])
df["id.resp_h"] = le.fit_transform(df["id.resp_h"])

In [56]:
df.head(5)

,id.orig_h,id.orig_p,id.resp_h,id.resp_p,proto,service,duration,orig_bytes,resp_bytes,conn_state,history,orig_pkts,orig_ip_bytes,resp_pkts,resp_ip_bytes,label
0,1360,60905.0,127613,23.0,1,0,2.998796,0.0,0.0,6,17,3.0,180.0,0.0,0.0,PartOfAHorizontalPortScan
1,1360,44301.0,1061393,23.0,1,0,0.000000,0.0,0.0,6,17,1.0,60.0,0.0,0.0,PartOfAHorizontalPortScan
2,1360,50244.0,83457,23.0,1,0,0.000000,0.0,0.0,6,17,1.0,60.0,0.0,0.0,PartOfAHorizontalPortScan
3,1360,34243.0,205149,49560.0,1,0,2.998804,0.0,0.0,6,17,3.0,180.0,0.0,0.0,Benign
4,1360,34840.0,195147,21288.0,1,0,0.000000,0.0,0.0,6,17,1.0,60.0,0.0,0.0,Benign

In [57]:
df.to_csv('iot23_malconcat_v2.csv')